### ISSUE TITLE
Kerb auth

### ISSUE THREAD

**Issue by svshivapuja** [singlestore-labs/sqlalchemy-singlestoredb#4]
How does this support kerberos authentication? I was able to connect through it but seems like the singlestore documentation says otherwise : https://docs.singlestore.com/db/v7.3/security/authentication/kerberos-authentication/assumptions-and-prerequisites/

**Comment by kesmit13** [comment]
That documentation was written before the Kerberos support was added to the SingleStoreDB Python client. However, if you have the gssapi Python package, Kerberos will work with this client as well. I'll make sure to update the documentation team to add this information to our docs.
